name: Sync Fork

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的午夜（UTC时间）执行
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保获取所有分支的历史记录

      - name: Sync Upstream for master
        run: |
          git checkout master  # 检出 master 分支
          git pull upstream master  # 从 upstream 拉取更新
          git push origin master  # 推送到 fork 的 master 分支

      - name: Sync Upstream for dev
        run: |
          git checkout dev  # 检出 develop 分支
          git pull upstream dev  # 从 upstream 拉取更新
          git push origin dev  # 推送到 fork 的 develop 分支

      - name: Check for Failure
        if: failure()
        run: |
          echo "[Error] Sync failed. Please check the logs for details."
          exit 1
